dist: trusty
addons:
  chrome: stable
before_install:
  - # start your web application and listen on `localhost`
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
language: node_js
services:
  - xvfb
node_js:
  - 'node'
#  - 'iojs'
# io.js has merged with the Node.js project again. There won't be any further io.js releases. All of the features in io.js are available in Node.js v4 and above.
before_script:
  - export DISPLAY=:99.0
